name: "Deploy infra to staging"
run-name:  infra setup of LeadSigma-Services

on:
  workflow_dispatch:
    branches:
      - "main"
    
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Create config.tf file
        run: |
          cat <<EOL > config.tf

          terraform {

            backend "s3" {

            bucket  =  "mybuckflow"

            encrypt = true

            key 	= "stateterraform_state.tfstate"

            region  = "ap-south-1"

            }
          
            required_providers {

            aws = {

              source  = "hashicorp/aws"

              version = "~> 5.23.1"

            }

            }

          }
          
          provider "aws" {

            region = "ap-south-1"

          }
          
          EOL
          
          echo "Terraform configuration file created: config.tf"

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238573859336:role/OIDC-deployment
          aws-region: ap-south-1
          role-session-name: OIDC-deployment
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4  
          
      - name: Terraform Init
        id: init
        env:
            AWS_BUCKET_NAME: "mybuckflow"
            AWS_BUCKET_KEY_NAME: "stateterraform_state.tfstate"
        run: terraform init 

      - name: Terraform Destroy
        run: terraform destroy